### ISSUE TITLE
Failed to install project dependencies

### ISSUE THREAD

**Issue by robinroy03** [honojs/create-hono#78]
### What version of Hono are you using?

0.14.2

### What runtime/platform is your app running on? (with version if possible)

Cloudflare workers

### What steps can reproduce the bug?

npm create hono@latest

### What is the expected behavior?

Honojs will be installed

### What do you see instead?

`npm create hono@latest`
```
> npx
> create-hono

create-hono version 0.14.2
? Target directory curl-llm
? Which template do you want to use? cloudflare-workers
? Do you want to install project dependencies? yes
? Which package manager do you want to use? npm
✔ Cloning the template
× Failed to install project dependencies
npm error code 1
npm error path /home/robin/Desktop
npm error command failed
npm error command sh -c create-hono
npm error A complete log of this run can be found in: /home/robin/.npm/_logs/2024-11-20T10_02_38_854Z-debug-0.log
```

```
node -v 
v20.18.0
```

```
npm -v 
10.8.1
```

```
cat /home/robin/.npm/_logs/2024-11-20T10_02_38_854Z-debug-0.log
0 verbose cli /snap/node/9209/bin/node /usr/local/bin/npm
1 info using npm@10.8.1
2 info using node@v20.18.0
3 silly config load:file:/usr/local/lib/node_modules/npm/npmrc
4 silly config load:file:/home/robin/Desktop/.npmrc
5 silly config load:file:/home/robin/.npmrc
6 silly config load:file:/snap/node/9209/etc/npmrc
7 verbose title npm create hono@latest
8 verbose argv "create" "hono@latest"
9 verbose logfile logs-max:10 dir:/home/robin/.npm/_logs/2024-11-20T10_02_38_854Z-
10 verbose logfile /home/robin/.npm/_logs/2024-11-20T10_02_38_854Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
14 http fetch GET 200 https://registry.npmjs.org/create-hono 1026ms (cache revalidated)
15 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
16 verbose stack Error: command failed
16 verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
16 verbose stack     at spawnWithShell (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
16 verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
16 verbose stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
16 verbose stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
16 verbose stack     at run (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/run-script.js:48:10)
16 verbose stack     at async exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:289:10)
16 verbose stack     at async Init.execCreate (/usr/local/lib/node_modules/npm/lib/commands/init.js:136:5)
16 verbose stack     at async Init.exec (/usr/local/lib/node_modules/npm/lib/commands/init.js:44:14)
16 verbose stack     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
17 error code 1
18 error path /home/robin/Desktop
19 error command failed
20 error command sh -c create-hono
21 verbose cwd /home/robin/Desktop
22 verbose os Linux 6.8.0-45-generic
23 verbose node v20.18.0
24 verbose npm  v10.8.1
25 verbose exit 1
26 verbose code 1
27 error A complete log of this run can be found in: /home/robin/.npm/_logs/2024-11-20T10_02_38_854Z-debug-0.log
```

### Additional information

I fixed it by installing without `project dependencies` and then doing `npm i` later.

**Comment by MathurAditya724** [comment]
I think we can close this @yusukebe, as there is no follow up

**Comment by yusukebe** [comment]
@MathurAditya724 Thank you for pinging! I'll close it.

**Comment by yusukebe** [comment]
@Yoder2k4 

Please create another issue.
